### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dream10201** [longportapp/openapi-go#64]
直接导致程序退出了，
相关代码：
main.go
![image](https://github.com/user-attachments/assets/11ec2916-61b2-4328-9660-e50893bab823)

core.go
![image](https://github.com/user-attachments/assets/09ac5c50-1ec7-4f65-8053-38fe607a1f81)

variable.go
![image](https://github.com/user-attachments/assets/2b58d61b-4f8e-4104-9f8b-3e86d0ca8205)

``` go
panic: runtime error: invalid memory address or nil pointer dereference                                                                                         
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x84f4ea]

goroutine 1 [running]:
github.com/longportapp/openapi-protocol/go/client.(*client).Close(0xc00014c1e0, {0x0, 0x0})
        /config/gopath/pkg/mod/github.com/longportapp/openapi-protocol/go@v0.4.0/client/client.go:410 +0xca
github.com/longportapp/openapi-go/trade.(*core).Close(...)
        /config/gopath/pkg/mod/github.com/longportapp/openapi-go@v0.15.0/trade/core.go:131
github.com/longportapp/openapi-go/trade.(*TradeContext).Close(...)
        /config/gopath/pkg/mod/github.com/longportapp/openapi-go@v0.15.0/trade/context.go:356
lb/core.Close()
        /code/go/lb/core/variable.go:67 +0x34
main.Close()
        /code/go/lb/main.go:70 +0x13
panic({0x8f11c0?, 0xda8d80?})
        /usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
github.com/longportapp/openapi-protocol/go/client.(*client).Do(0xc00014c000, {0xa48b60, 0xe20da0}, 0xc0001b4320, {0x0, 0x0, 0xc000158030?})
        /config/gopath/pkg/mod/github.com/longportapp/openapi-protocol/go@v0.4.0/client/client.go:336 +0xe2
github.com/longportapp/openapi-go/quote.(*core).Quote(0xc00039d800, {0xa48b60, 0xe20da0}, {0xc000433c20, 0x1, 0x1})
        /config/gopath/pkg/mod/github.com/longportapp/openapi-go@v0.15.0/quote/core.go:202 +0x124
github.com/longportapp/openapi-go/quote.(*QuoteContext).Quote(...)
        /config/gopath/pkg/mod/github.com/longportapp/openapi-go@v0.15.0/quote/context.go:111
lb/core.Run()
        /code/go/lb/core/core.go:73 +0x236
main.main()
        /code/go/lb/main.go:85 +0xca
```

**Comment by dream10201** [comment]
检查了以下，应该是网络问题导致的，但是直接panic是不是过了，返回个err让判断进行重连不行吗

**Comment by Patrick0308** [comment]
内部有重试机制的， panic 的确有问题。

**Comment by Patrick0308** [comment]
在 https://github.com/longportapp/openapi-protocol/pull/17 中修复
